Add CGNAT Range
librespeed/speedtest pull request #258
Opened 2019-11-27 05:31 UTC by agent-squirrel

I have added a regex to the getIP.php file for discovering CGNAT IP addresses. It may not be that common but at our ISP we route our CGNAT clients internally so they hot the speed test server with their CGNAT IP instead of real world. This allows the IP to be shown with a message explaining the CGNAT IP.

2019-11-27 06:13 UTC, adolfintel commented
Sounds good. Will test it and merge it ASAP

2022-02-12 16:19 UTC, ValZapod commented
I have 100.x ips too. So double NAT.

2022-03-30 18:50 UTC, Computroniks requested changes

2022-03-30 18:50 UTC, Computroniks commented on backend/getIP.php
> +if (preg_match('/^100\.([6-9][0-9]|1[0-2][0-7])\./', $ip) === 1) { // 100.64/10 CGNAT IPv4
This regex doesn't quite work. It allows addresses such as `100.63.0.0` but blocks addresses like `100.118.0.0`. Perhaps something like `/^100\.(6[4-9]|[7-9]\d|1[0-1]\d|12[0-7])\./` would work better. Here is an example of some of the tests https://regex101.com/r/6WAdkr/1

```suggestion
if (preg_match('/^100\.(6[4-9]|[7-9]\d|1[0-1]\d|12[0-7])\./', $ip) === 1) { // 100.64/10 CGNAT IPv4
```

2022-11-11 05:32 UTC, closed without merging