Updated Docker to use php8.2-apache as the upstream image.
librespeed/speedtest pull request #570
Opened 2023-08-09 20:38 UTC by zampettim

Updated to use php8.2-apache as the upstream image for Docker

2023-08-09 21:25 UTC, Quentame approved these changes

2023-11-03 10:12 UTC, stefanstidlffg commented
i would use 
`FROM php:8-apache`
for better long term updates
works as well

2023-11-03 10:13 UTC, stefanstidlffg commented on Dockerfile
> +FROM php:8.2-apache
FROM php:8-apache
will work too

2023-11-03 10:17 UTC, stefanstidlffg commented
duplicate of #522

2023-11-03 15:59 UTC, Quentame requested changes

2023-11-03 15:59 UTC, Quentame commented on Dockerfile
> +FROM php:8.2-apache
```suggestion
FROM php:8-apache
```

2023-11-03 16:01 UTC, Quentame commented
> duplicate of #522

Not really as this PR is focused in one subject, as a PR should be.
PR #522 is doing two different things, which is not a good practise.

2023-11-03 17:50 UTC, sstidl commented
> > duplicate of #522
> 
> Not really as this PR is focused in one subject, as a PR should be. PR #522 is doing two different things, which is not a good practise.

point taken ;-)

2023-11-03 21:48 UTC, sstidl approved these changes

2023-11-03 21:48 UTC, merged